<?php
session_start(); // Initialize the session
use OTPHP\TOTP;

require __DIR__ . '/../vendor/autoload.php'; 

$usuario = "fabio";

function generateSecret($usuario): string {
    $ga = new PHPGangsta\GoogleAuthenticator\GoogleAuthenticator();
    $secret = $ga->createSecret();
    $label = $usuario . '@fitpill.com';
    return $ga->getQRCodeGoogleUrl($label, $secret);
}

// Retrieve the user's secret key from the database (consult the example below)
$secret = generateSecret($usuario);

$otp = TOTP::create($secret);
$otp->setLabel($usuario . '@fitpill.com'); // Use the value of $usuario as the label

$qrCodeUri = $otp->getQrCodeUri(
    'https://api.qrserver.com/v1/create-qr-code/?data=' . urlencode($secret) . '&size=300x300&ecc=M',
    $secret
);
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../css/autenticar.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Register Authenticator</title>
</head>
<body class="body">
<div class="wrapper">
    <div class="loginform">
        <h1>Two-Factor Authentication Method</h1>
        <p>Scan this QR code with your authenticator app to set up two-factor authentication:</p>
        <div class="qrcode">
            <img src="<?php echo $qrCodeUri; ?>" alt="QR Code">
        </div>
        <p>After scanning the QR code, enter the six-digit code generated by your authenticator app to confirm the setup.</p>
        <form action="confirmar2fa.php" method="POST">
            <label for="codigo_2fa"></label>
            <div class="input-box">
                <input type="text" id="codigo_2fa" name="codigo_2fa">
                <button class="button" type="submit">Confirm</button>
                <i class="fa fa-lock"></i>
            </div>
        </form>
    </div>
</div>
</body>
</html>